trigger:
- main
- prerelease

resources:
  repositories:
  - repository: templates
    type: git
    name: DevopsTools/prodest-build-deploy-templates

stages:
  - template: buildDeployNuget.yml@templates
    parameters:
      Major: 0
      Minor: 1
      PatchAtual: 2
      LibraryName: Certificado.ICPBrasil